// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGz7eWN1-TlbNi5xlwQq1XI8gKu9gnZSk',
    appId: '1:470559283206:web:6c29133d67e411cd3a0b87',
    messagingSenderId: '470559283206',
    projectId: 'tasktrack-65b06',
    authDomain: 'tasktrack-65b06.firebaseapp.com',
    storageBucket: 'tasktrack-65b06.firebasestorage.app',
    measurementId: 'G-DW4PEJG55Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCauQGmjM7_gCpmRkPLq-dF6g5Cv3T65Vk',
    appId: '1:470559283206:android:5d9afd983e3a9fbb3a0b87',
    messagingSenderId: '470559283206',
    projectId: 'tasktrack-65b06',
    storageBucket: 'tasktrack-65b06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbJefZWcycXO5usrZ-kHojXS7LJ_sH3g',
    appId: '1:470559283206:ios:4d8517c406b0b08b3a0b87',
    messagingSenderId: '470559283206',
    projectId: 'tasktrack-65b06',
    storageBucket: 'tasktrack-65b06.firebasestorage.app',
    iosBundleId: 'com.example.taskTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzbJefZWcycXO5usrZ-kHojXS7LJ_sH3g',
    appId: '1:470559283206:ios:4d8517c406b0b08b3a0b87',
    messagingSenderId: '470559283206',
    projectId: 'tasktrack-65b06',
    storageBucket: 'tasktrack-65b06.firebasestorage.app',
    iosBundleId: 'com.example.taskTrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGz7eWN1-TlbNi5xlwQq1XI8gKu9gnZSk',
    appId: '1:470559283206:web:5744066e91cac7003a0b87',
    messagingSenderId: '470559283206',
    projectId: 'tasktrack-65b06',
    authDomain: 'tasktrack-65b06.firebaseapp.com',
    storageBucket: 'tasktrack-65b06.firebasestorage.app',
    measurementId: 'G-CFPZ23NCTS',
  );
}
